server:
  port: 8080
  error:
    include-message: always
spring:
  application:
    name: springexample
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) %replace(trace.id=\"%X{traceId}\" ){'trace.id=\"\" ',''}%replace(account.id=\"%X{accountId}\" ){'account.id=\"\" ',''}- %msg%n"
  level:
    com.bizzabo: INFO
    org.springframework: ERROR
---
spring:
  config.activate.on-profile: default
  application:
    name: springexample
server:
  error:
    include-exception: true
    include-stacktrace: always
---
spring:
  config.activate.on-profile: dev
  application:
    name: springexample
server:
  error:
    include-exception: true
    include-stacktrace: always
---
spring:
  config.activate.on-profile: stg
  application:
    name: springexample
---
spring:
  config.activate.on-profile: prod
  application:
    name: springexample
